In [1]:
import numpy as np

In [2]:
board = np.zeros((3, 3))
position = (1, 1)
player = 1
board[(1, 1)] = player
board[(1, 2)] = 2
X, Y = np.where(board == 0)
list(zip(X, Y))

[(0, 0), (0, 1), (0, 2), (1, 0), (2, 0), (2, 1), (2, 2)]

In [3]:
board

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 0., 0.]])

In [4]:
np.diagonal(board, offset=-1)

array([0., 0.])

In [5]:
lines = [board[i, :] for i in range(3)]
lines

[array([0., 0., 0.]), array([0., 1., 2.]), array([0., 0., 0.])]

In [6]:
lines += [board[:, i] for i in range(3)]
lines

[array([0., 0., 0.]),
 array([0., 1., 2.]),
 array([0., 0., 0.]),
 array([0., 0., 0.]),
 array([0., 1., 0.]),
 array([0., 2., 0.])]

In [7]:
[np.diagonal(board, offset=i) for i in range(-3, 3)]

[array([], dtype=float64),
 array([0.]),
 array([0., 0.]),
 array([0., 1., 0.]),
 array([0., 2.]),
 array([0.])]

In [8]:
[np.diagonal(board.T, offset=i) for i in range(-3, 3)]

[array([], dtype=float64),
 array([0.]),
 array([0., 2.]),
 array([0., 1., 0.]),
 array([0., 0.]),
 array([0.])]

In [91]:
class TicTacToe:
    def __init__(self, size=3):
        self.size = size
        self.board = np.zeros((size, size))
        self.players = [1, 2]
    
    def set(self, player, position):
        assert player in self.players, f'Invalid player {player}; only {self.players} allowed'
        # assert position in zip(range(self.size), range(self.size)), f'Position {position} not valid (max size = {self.size})'
        assert self.board[position] == 0, 'Position already occupied'
        self.board[position] = player
    
    def valid_moves(self):
        "returns list of valid (= empty) board positions"
        X, Y = np.where(board == 0)
        return list(zip(X, Y))
    
    def _get_lines(self):
        lines  = [self.board[i, :] for i in range(self.size)]
        lines += [self.board[:, i] for i in range(self.size)]
        lines += [np.diagonal(self.board, offset=i) for i in range(-self.size+1, self.size)]
        lines += [np.diagonal(np.fliplr(self.board), offset=i) for i in range(-self.size+1, self.size)]
        return lines
    
    def check_winner(self):
        lines = self._get_lines()
        for player in self.players:
            for line in lines:
                counter = 0
                for item in line:
                    if item == player:
                        counter += 1
                    else:
                        counter = 0
                    if counter == 3:
                        print(f"player {player} has won")
                        return player
    
    def set_state(self, board):
        self.board = board
    
    def __hash__(self):
        #return hash(self.board)
        #return tuple(self.board.flatten().astype(int))
        return hash(tuple(self.board.flatten().astype(int)))
    
    @staticmethod
    def from_state(board):
        assert type(board) == np.ndarray, "'board' must be numpy.ndarray"
        n, _ = board.shape
        game = TicTacToe(n)
        game.set_state(board)
        return game
                
    def show(self):
        print(self.board)


In [92]:
game = TicTacToe(size=3)
hash(game)

-4789650463397058604

In [70]:
class MCTS:
    def __init__(self, game, T=1):
        "T = max 'think' time"
        self.game = game
    
    def select(self, node) -> Node:
        pass
    
    def expand(self, node) -> None:
        pass

    def rollout(self, node) -> float:
        pass

    def backprop(self, value) -> None:
        pass

In [71]:
mcts = MCTS(game)